// <auto-generated />
using System;
using Terminals.Web.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Terminals.Web.Persistence.Migrations
{
    [DbContext(typeof(LocalAppDbContext))]
    [Migration("20260425102646_AddActivityLogs")]
    partial class AddActivityLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ActorEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.AllowedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("AllowedUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "",
                            Email = "admin@admin.com",
                            EmployeeId = 7300,
                            FullName = "Ø£Ø­Ù…Ø¯ Ø²ÙŠØ¯ Ø§Ù„Ø­Ø±Ø¨ÙŠ",
                            IsActive = true,
                            IsAdmin = true
                        });
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.Delegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Delegations");
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.DelegationTerminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DelegationId")
                        .HasColumnType("int");

                    b.Property<string>("TerminalId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("WasAssignedBefore")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DelegationId");

                    b.ToTable("DelegationTerminals");
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ø§Ù„Ù…Ø¨Ù†Ù‰ Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠ"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ø§Ù„Ù…Ø·Ù„Ø§Ø¹"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ø¨Ø±Ø¬ Ø§Ù„ØªØ­Ø±ÙŠØ±"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ØµØ¨Ø§Ø­ Ø§Ù„Ø³Ø§Ù„Ù…"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ø§Ù„Ø¬Ù‡Ø±Ø§Ø¡ - Ø­ÙƒÙˆÙ…Ø© Ù…ÙˆÙ„"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Ø§Ù„Ø¬Ù‡Ø±Ø§Ø¡ - ØªÙŠÙ…Ø§Ø¡"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Ø¬Ø§Ø¨Ø± Ø§Ù„Ø£Ø­Ù…Ø¯"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ø³Ø¹Ø¯ Ø§Ù„Ø¹Ø¨Ø¯Ø§Ù„Ù„Ù‡"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Ø§Ù„ØµÙ„ÙŠØ¨ÙŠØ©"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ø§Ù„Ù‚Ø±ÙŠÙ† - Ø­ÙƒÙˆÙ…Ø© Ù…ÙˆÙ„"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ù…Ø¨Ø§Ø±Ùƒ Ø§Ù„ÙƒØ¨ÙŠØ±"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ø§Ù„Ù†Ù‡Ø¶Ø©"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ØºØ±Ø¨ Ø§Ù„Ø¬Ù„ÙŠØ¨"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ù…ÙˆØ§Ù‚Ø¹ Ø£Ø®Ø±Ù‰"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Ø§Ù„Ø³Ø§Ù„Ù…ÙŠ"
                        });
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.TerminalRegionMap", b =>
                {
                    b.Property<string>("TerminalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("TerminalId");

                    b.HasIndex("RegionId");

                    b.ToTable("TerminalRegionMaps");
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.DelegationTerminal", b =>
                {
                    b.HasOne("Terminals.Web.Persistence.Entities.Delegation", "Delegation")
                        .WithMany("Terminals")
                        .HasForeignKey("DelegationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delegation");
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.TerminalRegionMap", b =>
                {
                    b.HasOne("Terminals.Web.Persistence.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Terminals.Web.Persistence.Entities.Delegation", b =>
                {
                    b.Navigation("Terminals");
                });
#pragma warning restore 612, 618
        }
    }
}
